name: Actions Workflow

on: [push]

jobs:
  run-github-ations:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        id: greet
        uses: actions/checkout@d0527efa5446816896365658676b36f79dd93d88
        with:
          who-to-greet: Aleksandr
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
