name: Actions Workflow

on: [push]

jobs:
  run-github-ations:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        id: greet
        uses: actions/github-actions-test@main
        with:
          who-to-greet: Aleksandr
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
